<?php
    include 'jargonLibrary.php';
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "\n";
echo "<head>\n";
echo "<meta name=\"viewport\" content=\"width=device-width, minimum-scale=1, maximum-scale=1\">\n";
echo "<title>Mobile Jargon File</title>\n";
echo "\n";
echo "<style>\n";
echo "    .imDiv\n";
echo "    {\n";
echo "    float: left;\n";
echo "    padding-right: 1em;\n";
echo "    padding-bottom: 1em;\n";
echo "    }\n";
echo "\n";
echo "    .black\n";
echo "    {\n";
echo "            color:black\n";
echo "    }\n";
echo "</style>\n";
echo "\n";
echo "<!--3 Files to include: 1 css and 2 js files-->\n";
echo "<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css\"></link>\n";
echo "<script src=\"http://code.jquery.com/jquery-1.6.4.min.js\"></script>\n";
echo "<script src=\"http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js\"></script>\n";
echo "\n";
echo "</head>\n";
echo "\n";
echo "<body width = \"100%\" class = \"bodyclass\">\n";
echo "\n";
echo "<section id = \"MainPage\" data-role = \"page\">\n";
echo "  <header data-role = \"header\">\n";
echo "    <h1>THE JARGON FILE</h1>  \n";
echo "  </header>\n";
echo "\n";
echo "	<div style=\"margin:20px auto; text-align: left;\">\n";
echo "		<h2>The Hacker Dictionary</h2>\n";
echo "	</div>\n";
echo "\n";
echo "  <div data-role = \"listview\">\n";
echo "	<div class =\"black\">\n";
echo "    <ul data-role = \"listview\">\n";
echo "       <li><a href = \"#NewSearch\" data-transition=\"fade\">NEW SEARCH</a></li>\n";
echo "	   <li></br></li>\n";
echo "       <li><a href = \"#TopRated\" data-transition=\"fade\">TOP RATED</a></li>\n";
echo "	   <li></br></li>\n";
echo "       <li><a href = \"random.php\" data-transition=\"fade\">RANDOM</a></li>\n";
echo "    </ul>\n";
echo "	</div>\n";
echo "	\n";
echo "  </div>  \n";
echo "\n";
echo "  <footer data-role = \"footer\" data-position=\"fixed\">\n";
echo "    <h1>Main Page</h1>\n";
echo "  </footer>\n";
echo "</section>\n";
echo "\n";
echo "<section id = \"NewSearch\" data-role = \"page\">\n";
echo "  <header data-role = \"header\">\n";
echo " \n";
echo "    <h1>The Hacker Dictionary</h1>\n";
echo "  </header>\n";
echo "      <div class = \"ui-btn-active\" data-role = \"navbar\">\n";
echo "\n";
echo "    <ul data-role = \"navbar\">\n";
echo "       <li><a href = \"#NewSearch\" data-transition=\"fade\">NEW SEARCH</a></li>\n";
echo "       <li><a href = \"#TopRated\" data-transition=\"fade\">TOP RATED</a></li>\n";
echo "       <li><a href = \"random.php\" data-transition=\"fade\">RANDOM</a></li>\n";
echo "    </ul>\n";
echo "\n";
echo "	\n";
echo "  </div> \n";
echo "\n";
echo "  <h1>SEARCH</h1>  \n";
echo "  \n";
echo "<p><i>Search for a term:</i></p>\n";
echo "<form method=\"post\" action=\"search.php\">\n";
echo "<input type=\"text\" name=\"searchtext\" value=\"\" >\n";
echo "<input type=\"submit\" name=\"Submit\" value=\"Go\">\n";
echo "</form>";
echo "  <footer data-role = \"footer\" data-position=\"fixed\">\n";
echo "		<div class = \"ui-btn-active\" data-role = \"navbar\">\n";
echo "			<ul data-role = \"navbar\">\n";
echo "				<li><a href=\"#MainPage\" data-role=\"navbar\" data-transition=\"fade\">Back to Main Page</a></li>\n";
echo "			</ul>\n";
echo "		</div>\n";
echo "  </footer>\n";
echo "</section>\n";
echo "\n";
echo "<section id = \"TopRated\" data-role = \"page\">\n";
echo "  \n";
echo "	<header data-role = \"header\">\n";
echo "		<h1>Top Rated</h1>\n";
echo "	</header>\n";
echo "     \n";
echo "	<div class = \"ui-btn-active\" data-role = \"navbar\">\n";
echo "		<ul data-role = \"navbar\">\n";
echo "			<li><a href = \"#NewSearch\" data-transition=\"fade\">NEW SEARCH</a></li>\n";
echo "			<li><a href = \"#TopRated\" data-transition=\"fade\">TOP RATED</a></li>\n";
echo "			<li><a href = \"random.php\" data-transition=\"fade\">RANDOM</a></li>\n";
echo "		</ul>\n";
echo "    </div> \n";
    $a_top = getTopRate();
    for($i = 0; $i < 3; $i++){
        $a_jarWordData = getJargon($a_top['name'][$i]);
        echo "	<h2>" . ($i+1) . " : " . $a_jarWordData['name'] . "</h2>\n";
        
        foreach($a_jarWordData['def'] as $item){
            echo "	<blockquote>" . $item . "</blockquote></br>\n";
        }
        
        echo "	<hr>\n";
    }
    
echo "  <footer data-role = \"footer\" data-position=\"fixed\">\n";
echo "		<div class = \"ui-btn-active\" data-role = \"navbar\">\n";
echo "			<ul data-role = \"navbar\">\n";
echo "				<li><a href=\"#MainPage\" data-role=\"navbar\" data-transition=\"fade\">Back to Main Page</a></li>\n";
echo "			</ul>\n";
echo "		</div>\n";
echo "  </footer>\n";
echo "</section>\n";
echo "</body>\n";
echo "</html>\n";

?>
